# Gradle performance & caching
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -XX:+UseG1GC -Dfile.encoding=UTF-8

# Kotlin daemon options
kotlin.daemon.jvmargs=-Xmx1536m -XX:+UseG1GC
kotlin.incremental=true
kotlin.mpp.stability.nowarn=true

# Dokka V2 Gradle plugin mode
org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers
